services:
  aplikasi_laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aplikasi_laravel
    restart: unless-stopped
    volumes:
      - ./app:/var/www/html
    networks:
      - portainer_networks

networks:
  portainer_networks:
    external: true
    name: portainer_networks
